config/routes.rb
Rails.application.routes.draw do

  root action: :home, controller: 'welcome'

  get 'help', action: :help, controller: 'welcome'
  get 'about', action: :about, controller: 'welcome'

  get 'login', action: :new, controller: 'sessions'
  post 'login', action: :create, controller: 'sessions'

  post 'log_out', action: :log_out_user, controller: 'sessions', as: :log_out

  scope 'czytelnik' do
    scope 'wypozyczenia' do
      get 'wszystkie', action: :rents_all, controller: 'readers', as: :readers_rents_all
      get 'aktywne', action: :rents_active, controller: 'readers', as: :readers_rents_active
      get 'oddane', action: :rents_inactive, controller: 'readers', as: :readers_rents_inactive
      get 'po_terminie', action: :rents_out_of_term, controller: 'readers', as: :readers_rents_out_of_term
    end
    get 'moje kary', action: :punishments, controller: 'readers', as: :readers_punishments
  end

  scope 'czytelnicy' do
    get 'wszyscy', action: :index, controller: 'readers', as: :all_readers
    get 'ranking', action: :best, controller: 'readers', as: :best_readers
  end

  scope 'wypozyczenia' do
    get 'wszystkie', action: :index, controller: 'rents', as: :all_rents
    get 'bierzace', action: :active, controller: 'rents', as: :active_rents
    get 'po_terminie', action: :out_of_term, controller: 'rents', as: :out_of_term_rents
    get 'oddane', action: :inactive, controller: 'rents', as: :inactive_rents
    get 'czytelnik/:id', action: :readers_rents, controller: 'rents', as: :admin_readers_rents
    post 'przedluz/:id', action: :prelongate, controller: 'rents', as: :prelongate
  end

  scope 'kary' do
    get 'czytelnik/:id', action: :readers_punishments, controller: 'punishments', as: :admin_readers_punishments
    get 'dodaj/:id', action: :new_punishment, controller: 'readers', as: :add_punishment
    post 'dodaj/:id', action: :create_punishment, controller: 'readers', as: :create_punishment
  end

  scope 'ksiazki' do
    get 'wszystkie', action: :index, controller: 'books', as: :all_books
    get 'dostepne', action: :available, controller: 'books', as: :available_books
    get 'wypozyczone', action: :rented, controller: 'books', as: :rented_books
    get 'popularnosc', action: :most_popular, controller: 'books', as: :popular_books

    get 'autor/:id', action: :author_books, controller: 'books', as: :autor_books
    get 'kategoria/:id', action: :category_books, controller: 'books', as: :category_books
    get 'wydawnictwo/:id', action: :publisher_books, controller: 'books', as: :publisher_books

    post 'wypozycz/:id', action: :rent, controller: 'books', as: :rent_book
    post 'return/:id', action: :return, controller: 'rents', as: :return_book
  end

  resources :rents
  resources :publishers
  resources :punishments
  resources :books
  resources :roles
  resources :employees
  resources :readers
  resources :categories
  resources :autors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/autor.rb
class Autor < ApplicationRecord
  has_many :books, dependent: :destroy
  
  def name
    "#{imie} #{nazwisko}"
  end

  def books
    Book.where("autor_id = #{id}")
  end
end

app/controllers/autors_controller.rb
# frozen_string_literal: true

class AutorsController < ApplicationController
  before_action :set_autor

  def index
    @autors = Autor.all
  end

  def new
    @autor = Autor.new
  end

  def edit; end

  def create
    @autor = Autor.new(autor_params)

    if @autor.save
      redirect_to autor_url(@autor), notice: 'Autor został dodany pomyślnie'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @autor.update(autor_params)
      redirect_to autor_url(@autor), notice: 'Dane Autora zostały zaktualizowane'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @autor.destroy
    redirect_to autors_url, notice: 'Autor został usunięty.'
  end

  private

  def set_autor
    @autor = Autor.find_by(id: params[:id])
  end

  def autor_params
    params.require(:autor).permit(:imie, :nazwisko)
  end
end

app/helpers/autors_helper.rb
module AutorsHelper
  def select_autor
    Autor.all.map do |autor|
      [autor.name, autor.id]
    end
  end
end

app/views/autors/_form.html.erb
<%= form_with(model: autor) do |form| %>
  <% if autor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(autor.errors.count, "error") %> prohibited this autor from being saved:</h2>

      <ul>
        <% autor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :imie %>
    <%= form.text_field :imie %>
  </div>

  <div class="field">
    <%= form.label :nazwisko %>
    <%= form.text_field :nazwisko %>
  </div>

  <div class="actions">
    <%= form.submit 'Dodaj / zapisz zmiany' %>
  </div>
<% end %>

app/views/autors/edit.html.erb
<h1>Edytuj Autor</h1>

<%= render 'form', autor: @autor %>

<%= link_to 'Wróć', autors_path %>

app/views/autors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Autorzy</h1>

<table>
  <thead>
    <tr>
      <th>Imie</th>
      <th>Nazwisko</th>
      <th>Książki autora</th>
      <th colspan="2">Akcje</th>
    </tr>
  </thead>

  <tbody>
    <% @autors.each do |autor| %>
      <tr>
        <td><%= autor.imie %></td>
        <td><%= autor.nazwisko %></td>
        <td><%= link_to 'Pokaż książki', autor_books_path(autor) %></td>
        <td><%= link_to 'Edytuj', edit_autor_path(autor) %></td>
        <td><%= link_to 'Usuń', autor, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj Autora', new_autor_path unless current_user.reader? %>

app/views/autors/new.html.erb
<h1>Dodaj Autora</h1>

<%= render 'form', autor: @autor %>

<%= link_to 'Wróć', autors_path %>

app/views/autors/show.html.erb
<p id="notice"><%= notice %></p>

<div class='show_data'>
  <p>
    <strong>Imie:</strong>
    <%= @autor.imie %>
  </p>

  <p>
    <strong>Nazwisko:</strong>
    <%= @autor.nazwisko %>
  </p>
</div>

<%= link_to 'Edytuj', edit_autor_path(@autor) %> |
<%= link_to 'Wróć', autors_path %> |
<%= link_to 'Dodaj Autora', new_autor_path %>