config/routes.rb
Rails.application.routes.draw do

  root action: :home, controller: 'welcome'

  get 'help', action: :help, controller: 'welcome'
  get 'about', action: :about, controller: 'welcome'

  get 'login', action: :new, controller: 'sessions'
  post 'login', action: :create, controller: 'sessions'

  post 'log_out', action: :log_out_user, controller: 'sessions', as: :log_out

  scope 'czytelnik' do
    scope 'wypozyczenia' do
      get 'wszystkie', action: :rents_all, controller: 'readers', as: :readers_rents_all
      get 'aktywne', action: :rents_active, controller: 'readers', as: :readers_rents_active
      get 'oddane', action: :rents_inactive, controller: 'readers', as: :readers_rents_inactive
      get 'po_terminie', action: :rents_out_of_term, controller: 'readers', as: :readers_rents_out_of_term
    end
    get 'moje kary', action: :punishments, controller: 'readers', as: :readers_punishments
  end

  scope 'czytelnicy' do
    get 'wszyscy', action: :index, controller: 'readers', as: :all_readers
    get 'ranking', action: :best, controller: 'readers', as: :best_readers
  end

  scope 'wypozyczenia' do
    get 'wszystkie', action: :index, controller: 'rents', as: :all_rents
    get 'bierzace', action: :active, controller: 'rents', as: :active_rents
    get 'po_terminie', action: :out_of_term, controller: 'rents', as: :out_of_term_rents
    get 'oddane', action: :inactive, controller: 'rents', as: :inactive_rents
    get 'czytelnik/:id', action: :readers_rents, controller: 'rents', as: :admin_readers_rents
    post 'przedluz/:id', action: :prelongate, controller: 'rents', as: :prelongate
  end

  scope 'kary' do
    get 'czytelnik/:id', action: :readers_punishments, controller: 'punishments', as: :admin_readers_punishments
    get 'dodaj/:id', action: :new_punishment, controller: 'readers', as: :add_punishment
    post 'dodaj/:id', action: :create_punishment, controller: 'readers', as: :create_punishment
  end

  scope 'ksiazki' do
    get 'wszystkie', action: :index, controller: 'books', as: :all_books
    get 'dostepne', action: :available, controller: 'books', as: :available_books
    get 'wypozyczone', action: :rented, controller: 'books', as: :rented_books
    get 'popularnosc', action: :most_popular, controller: 'books', as: :popular_books

    get 'autor/:id', action: :author_books, controller: 'books', as: :autor_books
    get 'kategoria/:id', action: :category_books, controller: 'books', as: :category_books
    get 'wydawnictwo/:id', action: :publisher_books, controller: 'books', as: :publisher_books

    post 'wypozycz/:id', action: :rent, controller: 'books', as: :rent_book
    post 'return/:id', action: :return, controller: 'rents', as: :return_book
  end

  resources :rents
  resources :publishers
  resources :punishments
  resources :books
  resources :roles
  resources :employees
  resources :readers
  resources :categories
  resources :autors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reader.rb
class Reader < ApplicationRecord
  has_many :punishments, dependent: :destroy
  has_many :rents, dependent: :destroy

  scope :best_reader, -> do
    joins('JOIN rents on rents.reader_id = readers.id')
    .group('readers.id')
    .order('count(readers.id) DESC')
  end

  def rents
    Rent.where("reader_id = #{id}")
  end

  def punishments
    Punishment.where("reader_id = #{id}")
  end

  def punishment_sum
    sql = "SELECT SUM(kwota) FROM punishments WHERE punishments.reader_id = #{id}"
    ActiveRecord::Base.connection.execute(sql).values[0][0] || 0
  end

  def rents_sum
    sql = "SELECT COUNT(*) FROM rents WHERE rents.reader_id = #{id}"
    ActiveRecord::Base.connection.execute(sql).values[0][0] || 0
  end

  def name
    "#{imie} #{nazwisko}"
  end

  def authenticate(pass)
    haslo == pass
  end

  def admin?
    false
  end

  def reader?
    true
  end

  def employee?
    false
  end
end

app/controllers/readers_controller.rb
# frozen_string_literal: true

class ReadersController < ApplicationController
  before_action :set_reader

  def index
    @readers = Reader.all
  end

  def show; end

  def rank_readers
    @readers = Reader.best_reader
  end

  def best
    @readers = Reader.best_reader
  end

  def new
    @reader = Reader.new
  end

  def rents_all
    @rents = current_user.rents
  end

  def rents_active
    @rents = current_user.rents.active
  end

  def rents_inactive
    @rents = current_user.rents.inactive
  end

  def rents_out_of_term
    @rents = current_user.rents.out_of_term
  end

  def punishments
    @punishments = current_user.punishments
  end

  def edit; end

  def create
    @reader = Reader.new(reader_params)

    if @reader.save
      if current_user.nil?
        log_in(@reader)
        redirect_to root_path, notice: 'Witamy!'
      else
        redirect_to reader_path(@reader),  notice: 'Dodano czytelnika pomyślnie.'
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @reader.update(reader_params)
      log_in(@reader)
      redirect_to reader_url(@reader), notice: 'Zaukualizowano dane czytelnika.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new_punishment
    @reader
  end

  def create_punishment
    punishment = Punishment.new(kwota: params[:punishment][:kwota], reader_id: params[:id])

    if punishment.save!
      redirect_to admin_readers_rents_path, notice: 'Dodano karę'
    else
      redirect_to admin_readers_rents_path, notice: 'Nie udało się dodać kary'
    end
  end

  def destroy
    @reader.destroy
    redirect_to readers_url, notice: 'Usunięto czytelnika pomyślnie'
  end

  private

  def set_reader
    @reader = Reader.find_by(id: params[:id])
  end

  def reader_params
    params.require(:reader).permit(:imie, :nazwisko, :telefon, :data_urodzenia, :email, :haslo)
  end
end

app/helpers/readers_helper.rb
module ReadersHelper
  def select_reader 
    Reader.all.map do |reader|
      [reader.name, reader.id]
    end
  end

  def book_status(rent)
    rent.data_oddania.nil? ? 'Wypozyczona' : 'Oddana'
  end

  def employee_rent(rent)
    rent.employee_rent_id.nil? ? 'Samodzielnie' : rent.employee_rent.name
  end
end

app/views/readers/_form.html.erb
<%= form_with(model: reader) do |form| %>
  <% if reader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reader.errors.count, "error") %> prohibited this reader from being saved:</h2>

      <ul>
        <% reader.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :imie %>
    <%= form.text_field :imie %>
  </div>

  <div class="field">
    <%= form.label :nazwisko %>
    <%= form.text_field :nazwisko %>
  </div>

  <div class="field">
    <%= form.label :telefon %>
    <%= form.text_field :telefon %>
  </div>

  <div class="field">
    <%= form.label :data_urodzenia %>
    <%= form.date_select :data_urodzenia, start_year: Date.today.year - 120, end_year: Date.today.year - 2 %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :haslo %>
    <%= form.password_field :haslo %>
  </div>

  <div class="actions">
    <%= form.submit current_user.nil? ? 'Zarejestruj się' : 'Dodaj / zapisz zmiany' %>
  </div>
<% end %>

app/views/readers/_form_punishment.html.erb
<%= form_for(:punishment, url: create_punishment_path(@reader)) do |form| %>

  <div class="field">
    <%= form.label :kwota %>
    <%= form.text_field :kwota %>
  </div>

  <div class="actions">
    <%= form.submit 'Dodaj karę' %>
  </div>
<% end %>

app/views/readers/best.html.erb
<p id="notice"><%= notice %></p>

<h1>Czytelnicy</h1>

<div class='show_data'>
  <%= link_to 'Wszyscy', :all_readers, class: 'nav'%>
  <%= link_to 'Ranking', :best_readers, class: 'out_of'%>
</div>

<table>
  <thead>
    <tr>
      <th>Imie</th>
      <th>Nazwisko</th>
      <th>Telefon</th>
      <th>Email</th>
      <th>Wypożyczenia</th>
      <th>Liczba wypożyczeń</th>
    </tr>
  </thead>

  <tbody>
    <% @readers.each do |reader| %>
      <tr>
        <td><%= reader.imie %></td>
        <td><%= reader.nazwisko %></td>
        <td><%= reader.telefon %></td>
        <td><%= reader.email %></td>
        <td><%= link_to 'Wypożyczenia', admin_readers_rents_path(reader), class: 'ref_table' %></td>
        <td><%= reader.rents_sum %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj Czytelnika', new_reader_path %>

app/views/readers/edit.html.erb
<h1>Edytuj Czytelnika</h1>

<%= render 'form', reader: @reader %>

<%= link_to 'Pokaż', @reader %> |
<%= link_to 'Wróć', readers_path %>

app/views/readers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Czytelnicy</h1>

<table>
  <thead>
    <tr>
      <th>Imie</th>
      <th>Nazwisko</th>
      <th>Telefon</th>
      <th>Data urodzenia</th>
      <th>Email</th>
      <th>Wypożyczenia</th>
      <th>Liczba wypożyczeń</th>
      <th>Kary</th>
      <th>Suma kar</th>
      <th colspan="3">Akcje</th>
    </tr>
  </thead>

  <tbody>
    <% @readers.each do |reader| %>
      <tr>
        <td><%= reader.imie %></td>
        <td><%= reader.nazwisko %></td>
        <td><%= reader.telefon %></td>
        <td><%= reader.data_urodzenia %></td>
        <td><%= reader.email %></td>
        <td><%= link_to 'Wypożyczenia', admin_readers_rents_path(reader), class: 'ref_table' %></td>
        <td><%= reader.rents_sum %></td>
        <td><%= link_to 'Naliczone kary', admin_readers_punishments_path(reader), class: 'ref_table' %></td>
        <td><%= reader.punishment_sum %></td>
        <td><%= link_to 'Pokaż', reader %></td>
        <td><%= link_to 'Edytuj', edit_reader_path(reader) %></td>
        <td><%= link_to 'Usuń', reader, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj Czytelnika', new_reader_path %>

app/views/readers/new.html.erb
<% if current_user.nil? %>
  <h1>Uzupełnij swoje dane</h1>
<% else %>
  <h1>Dodaj Czytelnika</h1>
<% end %>

<%= render 'form', reader: @reader %>

app/views/readers/new_punishment.html.erb
<h1><%= "Nadaj karę dla #{@reader.name}"%></h1>
<%= render 'form_punishment'%>

app/views/readers/punishments.html.erb
<p id="notice"><%= notice %></p>

<h1>Wystawione kary</h1>

<table>
  <thead>
    <tr>
      <th>Kwota</th>
      <th>Data wystawienia</th>
    </tr>
  </thead>

  <tbody>
    <% @punishments.each do |punishment| %>
      <tr>
        <td><%= punishment.kwota %></td>
        <td><%= punishment.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/readers/rents.html.erb
<p id="notice"><%= notice %></p>

<h1>Moje wypożyczenia <%= "(#{@rents.count})" %></h1>

<table>
  <thead>
    <tr>
      <th>Książka</th>
      <th>Data wypozyczenia</th>
      <th>Pracownik wypożyczający</th>
      <th>Planowana data oddania</th>
      <th>Status</th>
      <th >Akcje</th>
    </tr>
  </thead>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td><%= link_to rent.book.tytul, rent.book, class: 'ref_table'%></td>
        <td><%= rent.data_wypozyczenia %></td>
        <td><%= link_to employee_rent(rent), rent.employee_rent, class: 'ref_table' %></td>
        <td><%= rent.planowana_data_oddania %></td>
        <td><%= book_status(rent) %></td>
        <td><%= link_to 'Przedłuż', prelongate_path(rent), method: "post" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/readers/rents_active.html.erb
<p id="notice"><%= notice %></p>

<h1>Moje wypożyczenia <%= "(#{@rents.count})" %></h1>

<div class='show_data'>
  <%= link_to 'Wszystkie', :readers_rents_all, class: 'nav' %>
  <%= link_to 'Bierzące',  :readers_rents_active, class: 'nav' %>
  <%= link_to 'Po czasie', :readers_rents_out_of_term, class: 'out_of' %>
  <%= link_to 'Oddane', :readers_rents_inactive, class: 'nav' %>
</div>

<table>
  <thead>
    <tr>
      <th>Książka</th>
      <th>Data wypozyczenia</th>
      <th>Pracownik wypożyczający</th>
      <th>Planowana data oddania</th>
      <th>Status</th>
      <th >Akcje</th>
    </tr>
  </thead>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td><%= link_to rent.book.tytul, rent.book, class: 'ref_table'%></td>
        <td><%= rent.data_wypozyczenia %></td>
        <td><%= employee_rent(rent) %></td>
        <td><%= rent.planowana_data_oddania %></td>
        <td><%= book_status(rent) %></td>
        <td><%= link_to 'Przedłuż', prelongate_path(rent), method: "post" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/readers/rents_all.html.erb
<p id="notice"><%= notice %></p>

<h1>Moje wypożyczenia <%= "(#{@rents.count})" %></h1>

<div class='show_data'>
  <%= link_to 'Wszystkie', :readers_rents_all, class: 'nav' %>
  <%= link_to 'Bierzące',  :readers_rents_active, class: 'nav' %>
  <%= link_to 'Po czasie', :readers_rents_out_of_term, class: 'out_of' %>
  <%= link_to 'Oddane', :readers_rents_inactive, class: 'nav' %>
</div>

<table>
  <thead>
    <tr>
      <th>Książka</th>
      <th>Data wypozyczenia</th>
      <th>Pracownik wypożyczający</th>
      <th>Planowana data oddania</th>
      <th>Data oddania</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td><%= link_to rent.book.tytul, rent.book, class: 'ref_table'%></td>
        <td><%= rent.data_wypozyczenia %></td>
        <td><%= employee_rent(rent) %></td>
        <td><%= rent.planowana_data_oddania %></td>
        <td><%= rent.data_oddania %></td>
        <td><%= book_status(rent) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/readers/rents_inactive.html.erb
<p id="notice"><%= notice %></p>

<h1>Moje oddane wypożyczenia <%= "(#{@rents.count})" %></h1>

<div class='show_data'>
  <%= link_to 'Wszystkie', :readers_rents_all, class: 'nav' %>
  <%= link_to 'Bierzące',  :readers_rents_active, class: 'nav' %>
  <%= link_to 'Po czasie', :readers_rents_out_of_term, class: 'out_of' %>
  <%= link_to 'Oddane', :readers_rents_inactive, class: 'nav' %>
</div>

<table>
  <thead>
    <tr>
      <th>Książka</th>
      <th>Data wypozyczenia</th>
      <th>Pracownik wypożyczający</th>
      <th>Planowana data oddania</th>
      <th>Data oddania</th>
      <th>Pracownik oddający</th>
    </tr>
  </thead>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td><%= link_to rent.book.tytul, rent.book, class: 'ref_table'%></td>
        <td><%= rent.data_wypozyczenia %></td>
        <td><%= employee_rent(rent) %></td>
        <td><%= rent.planowana_data_oddania %></td>
        <td><%= rent.data_oddania %></td>
        <td><%= employee_return(rent) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/readers/rents_out_of_term.html.erb
<p id="notice"><%= notice %></p>

<h1>Wypożyczenia po terminie <%= "(#{@rents.count})" %></h1>

<div class='show_data'>
  <%= link_to 'Wszystkie', :readers_rents_all, class: 'nav' %>
  <%= link_to 'Bierzące',  :readers_rents_active, class: 'nav' %>
  <%= link_to 'Po czasie', :readers_rents_out_of_term, class: 'out_of' %>
  <%= link_to 'Oddane', :readers_rents_inactive, class: 'nav' %>
</div>

<table>
  <thead>
    <tr>
      <th>Książka</th>
      <th>Data wypozyczenia</th>
      <th>Pracownik wypożyczający</th>
      <th>Planowana data oddania</th>
      <th>Status</th>
      <th >Akcje</th>
    </tr>
  </thead>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td><%= link_to rent.book.tytul, rent.book, class: 'ref_table'%></td>
        <td><%= rent.data_wypozyczenia %></td>
        <td><%= employee_rent(rent) %></td>
        <td><%= rent.planowana_data_oddania %></td>
        <td><%= book_status(rent) %></td>
        <td><%= link_to 'Przedłuż', prelongate_path(rent), method: "post" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/readers/show.html.erb
<p id="notice"><%= notice %></p>
<div class='show_data'>
  <p>
    <strong>Imie:</strong>
    <%= @reader.imie %>
  </p>

  <p>
    <strong>Nazwisko:</strong>
    <%= @reader.nazwisko %>
  </p>

  <p>
    <strong>Telefon:</strong>
    <%= @reader.telefon %>
  </p>

  <p>
    <strong>Data urodzenia:</strong>
    <%= @reader.data_urodzenia %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @reader.email %>
  </p>

</div>

<%= link_to 'Edytuj', edit_reader_path(@reader) %> |
<%= link_to 'Wróć', readers_path %> |
<%= link_to 'Dodaj Czytelnika', new_reader_path %>