config/routes.rb
Rails.application.routes.draw do

  root action: :home, controller: 'welcome'

  get 'help', action: :help, controller: 'welcome'
  get 'about', action: :about, controller: 'welcome'

  get 'login', action: :new, controller: 'sessions'
  post 'login', action: :create, controller: 'sessions'

  post 'log_out', action: :log_out_user, controller: 'sessions', as: :log_out

  scope 'czytelnik' do
    scope 'wypozyczenia' do
      get 'wszystkie', action: :rents_all, controller: 'readers', as: :readers_rents_all
      get 'aktywne', action: :rents_active, controller: 'readers', as: :readers_rents_active
      get 'oddane', action: :rents_inactive, controller: 'readers', as: :readers_rents_inactive
      get 'po_terminie', action: :rents_out_of_term, controller: 'readers', as: :readers_rents_out_of_term
    end
    get 'moje kary', action: :punishments, controller: 'readers', as: :readers_punishments
  end

  scope 'czytelnicy' do
    get 'wszyscy', action: :index, controller: 'readers', as: :all_readers
    get 'ranking', action: :best, controller: 'readers', as: :best_readers
  end

  scope 'wypozyczenia' do
    get 'wszystkie', action: :index, controller: 'rents', as: :all_rents
    get 'bierzace', action: :active, controller: 'rents', as: :active_rents
    get 'po_terminie', action: :out_of_term, controller: 'rents', as: :out_of_term_rents
    get 'oddane', action: :inactive, controller: 'rents', as: :inactive_rents
    get 'czytelnik/:id', action: :readers_rents, controller: 'rents', as: :admin_readers_rents
    post 'przedluz/:id', action: :prelongate, controller: 'rents', as: :prelongate
  end

  scope 'kary' do
    get 'czytelnik/:id', action: :readers_punishments, controller: 'punishments', as: :admin_readers_punishments
    get 'dodaj/:id', action: :new_punishment, controller: 'readers', as: :add_punishment
    post 'dodaj/:id', action: :create_punishment, controller: 'readers', as: :create_punishment
  end

  scope 'ksiazki' do
    get 'wszystkie', action: :index, controller: 'books', as: :all_books
    get 'dostepne', action: :available, controller: 'books', as: :available_books
    get 'wypozyczone', action: :rented, controller: 'books', as: :rented_books
    get 'popularnosc', action: :most_popular, controller: 'books', as: :popular_books

    get 'autor/:id', action: :author_books, controller: 'books', as: :autor_books
    get 'kategoria/:id', action: :category_books, controller: 'books', as: :category_books
    get 'wydawnictwo/:id', action: :publisher_books, controller: 'books', as: :publisher_books

    post 'wypozycz/:id', action: :rent, controller: 'books', as: :rent_book
    post 'return/:id', action: :return, controller: 'rents', as: :return_book
  end

  resources :rents
  resources :publishers
  resources :punishments
  resources :books
  resources :roles
  resources :employees
  resources :readers
  resources :categories
  resources :autors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :book
  belongs_to :reader
  belongs_to :employee_rent, class_name: 'Employee', foreign_key: 'employee_rent_id', optional: true
  belongs_to :employee_return, class_name: 'Employee', foreign_key: 'employee_return_id', optional: true

  scope :active, -> { where('data_oddania is NULL') }

  scope :inactive, -> { where('data_oddania is not null') }

  scope :out_of_term, -> { where('data_oddania is NULL and planowana_data_oddania < ?', Date.today) }

  def return_date
    return 'Książka nie została oddana' if data_oddania.nil?

    data_oddania
  end

end

app/controllers/rents_controller.rb
# frozen_string_literal: true

class RentsController < ApplicationController
  before_action :set_rent

  def index
    @rents = Rent.all
  end

  def inactive
    @rents = Rent.inactive
  end

  def active
    @rents = Rent.active
  end

  def out_of_term
    @out_of = true
    @rents = Rent.out_of_term
  end

  def show; end

  def new
    @rent = Rent.new
  end

  def return
    employee_id = current_user.employee? ? current_user.id : nil
    if @rent.data_oddania.nil?
      @rent.update(data_oddania: Date.today, employee_return_id: employee_id)
      redirect_to :all_rents
    else
      redirect_to :all_rents, notice: 'To wypożyczenie jest już oddane'
    end

  end

  def readers_rents
    @reader = Reader.find_by(id: params[:id])
  end

  def prelongate
    @rent.planowana_data_oddania += 1.month

    redirect_to :readers_rents_all, notice: 'Data oddania została przedłużona' if @rent.save!
  end

  def edit; end

  def create
    @rent = Rent.new(rent_params)
    if @rent.save
      redirect_to :all_rents, notice: 'Dodano wypożyczenie.' unless current_user.reader?
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @rent.update(rent_params)
      redirect_to rent_url(@rent), notice: 'Zaktualizowano wypożyczenie.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @rent.destroy
    redirect_to rents_url, notice: 'Usunięto wypożyczenie'
  end

  private

  def set_rent
    @rent = Rent.find_by(id: params[:id])
  end

  def rent_params
    params.require(:rent).permit(:planowana_data_oddania, :data_wypozyczenia, :data_oddania, :book_id, :reader_id,
                                 :employee_rent_id)
  end
end

app/helpers/rents_helper.rb
module RentsHelper
  def employee_rent(rent)
    rent.employee_rent_id.nil? ? 'Samodzielnie' : rent.employee_rent.name
  end

  def employee_return(rent)
    rent.employee_return_id.nil? ? 'Administrator' : rent.employee_return.name
  end
end

app/views/rents/_form.html.erb
<%= form_with(model: rent) do |form| %>
  <% if rent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rent.errors.count, "error") %> prohibited this rent from being saved:</h2>

      <ul>
        <% rent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Książka %>
    <%= form.select :book_id, options_for_select(select_book, rent.book) %>
  </div>

  <div class="field">
    <%= form.label :Czytelnik %>
    <%= form.select :reader_id, options_for_select(select_reader, rent.reader) %>
  </div>

  <div class="field">
    <%= form.label :data_wypozyczenia %>
    <%= form.date_select :data_wypozyczenia, selected: Date.today, start_year: Date.today.year %>
  </div>

  <div class="field">
    <%= form.label :planowana_data_oddania %>
    <%= form.date_select :planowana_data_oddania, selected: Date.today + 2.months, start_year: Date.today.year %>
  </div>

  <div class="field">
    <%= form.label 'Pracownik wypożyczający' %>
    <%= form.select :employee_rent_id, options_for_select(select_employee, rent.employee_rent) %>
  </div>

  <div class="actions">
    <%= form.submit 'Dodaj / zapisz zmiany' %>
  </div>
<% end %>

app/views/rents/_table.html.erb
<div class='show_data'>
  <%=link_to 'Wszystkie' , :all_rents       , class: 'nav' %>
  <%=link_to 'Oddane' , :inactive_rents       , class: 'nav' %>
  <%=link_to 'Bierzące' , :active_rents       , class: 'nav' %>
  <%=link_to 'Po terminie' , :out_of_term_rents       , class: 'out_of' %>
  <%= link_to 'Dodaj Wypożyczenie', new_rent_path %>
</div>

<table>
  <thead>
    <tr>
      <th>Książka</th>
      <th>Czytelnik</th>
      <th>Data wypozyczenia</th>
      <th>Pracownik wypożyczający</th>
      <th>Planowana data oddania</th>
      <th>Data oddania</th>
      <% if @out_of %>
        <th colspan="4">Akcje</th>
      <% else %>
        <th colspan="3">Akcje</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td><%= link_to rent.book.tytul, rent.book, class: 'ref_table'%></td>
        <td><%= link_to rent.reader.name, rent.reader, class: 'ref_table' %></td>
        <td><%= rent.data_wypozyczenia %></td>
        <td><%= link_to employee_rent(rent), rent.employee_rent, class: 'ref_table' %></td>
        <td><%= rent.planowana_data_oddania %></td>
        <td><%= rent.return_date %></td>
        <td><%= link_to 'Oddaj', return_book_path(rent), method: :post, class: return_button(rent) %></td>

        <% if @out_of%>
          <td><%= link_to 'Dodaj karę', add_punishment_path(rent.reader), class: 'out_of' %></td>
        <% end %>

        <td><%= link_to 'Edytuj', edit_rent_path(rent) %></td>
        <td><%= link_to 'Usuń', rent, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rents/active.html.erb
<p id="notice"><%= notice %></p>

<h1>Wypożyczenia bierzące</h1>

<%= render 'table' %>

app/views/rents/edit.html.erb
<h1>Edytuj Wypożyczenie</h1>

<%= render 'form', rent: @rent %>

<%= link_to 'Pokaż', @rent %> |
<%= link_to 'Wróć', rents_path %>

app/views/rents/inactive.html.erb
<p id="notice"><%= notice %></p>

<h1>Wypożyczenia oddane</h1>

<%= render 'table' %>

app/views/rents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wypożyczenia</h1>

<%= render 'table' %>

app/views/rents/new.html.erb
<h1>Dodaj Wypożyczenie</h1>

<%= render 'form', rent: @rent %>

<%= link_to 'Wróć', rents_path %>

app/views/rents/out_of_term.html.erb
<p id="notice"><%= notice %></p>

<h1>Wypożyczenia po terminie</h1>

<%= render 'table' %>

app/views/rents/readers_rents.html.erb
<p id="notice"><%= notice %></p>

<h1><%= "#{@reader.name} - wypożyczenia" %></h1>

<table>
  <thead>
    <tr>
      <th>Książka</th>
      <th>Data wypozyczenia</th>
      <th>Pracownik wypożyczający</th>
      <th>Planowana data oddania</th>
      <th>Data oddania</th>
      <th>Status</th>
      <th colspan="4">Akcje</th>
    </tr>
  </thead>

  <tbody>
    <% @reader.rents.each do |rent| %>
      <tr>
        <td><%= link_to rent.book.tytul, rent.book, class: 'ref_table'%></td>
        <td><%= rent.data_wypozyczenia %></td>
        <td><%= link_to employee_rent(rent), rent.employee_rent, class: 'ref_table' %></td>
        <td><%= rent.planowana_data_oddania %></td>
        <td><%= rent.return_date %></td>
        <td><%= book_status(rent) %></td>
        <td><%= link_to 'Oddaj', return_book_path(rent), method: :post, class: return_button(rent) %></td>
        <td><%= link_to 'Dodaj karę', add_punishment_path(@reader) %></td>
        <td><%= link_to 'Edytuj', edit_rent_path(rent) %></td>
        <td><%= link_to 'Usuń', rent, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj Wypożyczenie', new_rent_path %>