config/routes.rb
Rails.application.routes.draw do

  root action: :home, controller: 'welcome'

  get 'help', action: :help, controller: 'welcome'
  get 'about', action: :about, controller: 'welcome'

  get 'login', action: :new, controller: 'sessions'
  post 'login', action: :create, controller: 'sessions'

  post 'log_out', action: :log_out_user, controller: 'sessions', as: :log_out

  scope 'czytelnik' do
    scope 'wypozyczenia' do
      get 'wszystkie', action: :rents_all, controller: 'readers', as: :readers_rents_all
      get 'aktywne', action: :rents_active, controller: 'readers', as: :readers_rents_active
      get 'oddane', action: :rents_inactive, controller: 'readers', as: :readers_rents_inactive
      get 'po_terminie', action: :rents_out_of_term, controller: 'readers', as: :readers_rents_out_of_term
    end
    get 'moje kary', action: :punishments, controller: 'readers', as: :readers_punishments
  end

  scope 'czytelnicy' do
    get 'wszyscy', action: :index, controller: 'readers', as: :all_readers
    get 'ranking', action: :best, controller: 'readers', as: :best_readers
  end

  scope 'wypozyczenia' do
    get 'wszystkie', action: :index, controller: 'rents', as: :all_rents
    get 'bierzace', action: :active, controller: 'rents', as: :active_rents
    get 'po_terminie', action: :out_of_term, controller: 'rents', as: :out_of_term_rents
    get 'oddane', action: :inactive, controller: 'rents', as: :inactive_rents
    get 'czytelnik/:id', action: :readers_rents, controller: 'rents', as: :admin_readers_rents
    post 'przedluz/:id', action: :prelongate, controller: 'rents', as: :prelongate
  end

  scope 'kary' do
    get 'czytelnik/:id', action: :readers_punishments, controller: 'punishments', as: :admin_readers_punishments
    get 'dodaj/:id', action: :new_punishment, controller: 'readers', as: :add_punishment
    post 'dodaj/:id', action: :create_punishment, controller: 'readers', as: :create_punishment
  end

  scope 'ksiazki' do
    get 'wszystkie', action: :index, controller: 'books', as: :all_books
    get 'dostepne', action: :available, controller: 'books', as: :available_books
    get 'wypozyczone', action: :rented, controller: 'books', as: :rented_books
    get 'popularnosc', action: :most_popular, controller: 'books', as: :popular_books

    get 'autor/:id', action: :author_books, controller: 'books', as: :autor_books
    get 'kategoria/:id', action: :category_books, controller: 'books', as: :category_books
    get 'wydawnictwo/:id', action: :publisher_books, controller: 'books', as: :publisher_books

    post 'wypozycz/:id', action: :rent, controller: 'books', as: :rent_book
    post 'return/:id', action: :return, controller: 'rents', as: :return_book
  end

  resources :rents
  resources :publishers
  resources :punishments
  resources :books
  resources :roles
  resources :employees
  resources :readers
  resources :categories
  resources :autors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy

  def books
    Book.where("category_id = #{id}")
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to category_url(@category), notice: 'Kategoria została dodana pomyślnie'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @category.update(category_params)
      redirect_to category_url(@category), notice: 'Kategoria została zaukualizowana.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy

    redirect_to categories_url, notice: 'Usunięto kategorie pomyślnie.'
  end

  private

  def set_category
    @category = Category.find_by(id: params[:id])
  end

  def category_params
    params.require(:category).permit(:nazwa)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def select_category
    Category.all.map do |category|
      [category.nazwa, category.id]
    end
  end
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nazwa %>
    <%= form.text_field :nazwa %>
  </div>

  <div class="actions">
    <%= form.submit 'Dodaj / zapisz zmiany' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edytuj Kategorię</h1>

<%= render 'form', category: @category %>

<%= link_to 'Wróć', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kategorie książek</h1>

<table>
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Książki danej kategorii</th>
      <th colspan="2">Akcje</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.nazwa %></td>
        <td><%= link_to 'Pokaż książki', category_books_path(category) %></td>
        <td><%= link_to 'Edytuj', edit_category_path(category) %></td>
        <td><%= link_to 'Usuń', category, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj Kategorię', new_category_path unless current_user.reader?%>

app/views/categories/new.html.erb
<h1>Dodaj kategorię</h1>

<%= render 'form', category: @category %>

<%= link_to 'Wróć', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<div class='show_data'>
  <p>
    <strong>Nazwa:</strong>
    <%= @category.nazwa %>
  </p>
</div>
<%= link_to 'Edytuj', edit_category_path(@category) %> |
<%= link_to 'Wróć', categories_path %> |
<%= link_to 'Dodaj Kategorie', new_category_path %>